#!/usr/bin/env bash
set -euo pipefail

# Idempotent FSL license header sweep.
#
# Walks `crates/**/*.rs` and `ui/src/**/*.{ts,tsx}` and prepends
#   // Copyright 2026 Alexandre Obellianne
#   // Licensed under the Functional Source License 1.1 (FSL-1.1-ALv2). See LICENSE.
#   <blank line>
# to any file that does NOT already mention "Functional Source License"
# or "FSL-1.1-ALv2" in its first 20 lines.
#
# Safe to run repeatedly: files that already carry the FSL header are skipped.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

HDR1='// Copyright 2026 Alexandre Obellianne'
HDR2='// Licensed under the Functional Source License 1.1 (FSL-1.1-ALv2). See LICENSE.'

added=0
skipped=0

prepend_header() {
  local file="$1"

  # Skip if the FSL header is already present in the first 20 lines.
  if head -n 20 "$file" | grep -q -E 'Functional Source License|FSL-1.1-ALv2'; then
    echo "skipped: $file"
    skipped=$((skipped + 1))
    return 0
  fi

  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n%s\n\n' "$HDR1" "$HDR2"
    cat "$file"
  } > "$tmp"
  mv "$tmp" "$file"

  echo "added: $file"
  added=$((added + 1))
}

# Rust sources.
while IFS= read -r -d '' file; do
  prepend_header "$file"
done < <(find crates -type f -name '*.rs' -print0)

# UI sources. Skip `ui/src/api/generated/` — ts-rs rewrites those files (they
# say "Do not edit this file manually"), so a header would not survive regen.
while IFS= read -r -d '' file; do
  prepend_header "$file"
done < <(find ui/src -type f \( -name '*.ts' -o -name '*.tsx' \) \
  -not -path '*/api/generated/*' -print0)

echo ""
echo "Summary: $added added, $skipped skipped."
