#!/usr/bin/env bash
set -euo pipefail

# Verify every TOML key in `config.toml.example` is mentioned in
# `docs/configuration.md`.
#
# Note: `docs/configuration.md` is generated as part of plan-04 task #3
# (README/docs reorg). If the file does not yet exist, this script
# exits 0 with a notice so that task ordering can slip without breaking CI.
#
# Parsing rule: any line in the example that matches `^[a-zA-Z_]+ *=`
# is treated as a top-level key (we ignore nested table headers; the
# generated doc lists keys flat under their section). For each key, we
# require the key name to appear somewhere in `docs/configuration.md`.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXAMPLE="$REPO_ROOT/config.toml.example"
DOC="$REPO_ROOT/docs/configuration.md"

if [ ! -f "$EXAMPLE" ]; then
  echo "ERROR: $EXAMPLE not found." >&2
  exit 1
fi

if [ ! -f "$DOC" ]; then
  echo "NOTICE: $DOC does not exist yet (generated by plan-04 task #3). Skipping check."
  exit 0
fi

missing=()

# Extract candidate keys. Strip leading whitespace, take the part before "=",
# trim trailing spaces. Only accept identifiers (letters, digits, underscore).
keys=$(
  grep -E '^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]* *=' "$EXAMPLE" \
    | sed -E 's/^[[:space:]]*([a-zA-Z_][a-zA-Z0-9_]*) *=.*/\1/' \
    | sort -u
)

for key in $keys; do
  if ! grep -q -F -- "$key" "$DOC"; then
    missing+=("$key")
  fi
done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "ERROR: the following keys from config.toml.example are missing from docs/configuration.md:" >&2
  for key in "${missing[@]}"; do
    echo "  - $key" >&2
  done
  exit 1
fi

echo "OK: all $(printf '%s\n' "$keys" | wc -l | tr -d ' ') keys from config.toml.example are documented."
