// Copyright 2026 Alexandre Obellianne
// Licensed under the Functional Source License 1.1 (FSL-1.1-ALv2). See LICENSE.

//! Master-key bootstrap (04_architecture.md §3.2).
//!
//! Three resolution sources, tried in order:
//! 1. `MAESTRO_SECRET_KEY` env var — 64-character hex.
//! 2. `${data_dir}/secret.key` — 32 raw bytes, file mode `0600`.
//! 3. If `allow_auto_generate` is true, generate a fresh 32-byte key, write
//!    it to `${data_dir}/secret.key` with mode `0600`, and return.
//!
//! If none of the three apply, the caller falls back to degraded mode and
//! `SystemStatus` surfaces a critical `master_key_unavailable` warning.

use std::fs::OpenOptions;
use std::io::Write;
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::OpenOptionsExt;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::error::{MaestroError, Result};

/// 32-byte deployment master key. Wraps the raw bytes in a `Zeroize`-on-drop
/// container so the key is wiped from memory when the manager is destroyed.
#[derive(ZeroizeOnDrop, Zeroize)]
pub struct MasterKey([u8; 32]);

impl std::fmt::Debug for MasterKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never leak the key bytes through Debug.
        f.debug_struct("MasterKey").field("bytes", &"<redacted>").finish()
    }
}

impl MasterKey {
    /// Parse a 64-character hex string (the format used by the
    /// `MAESTRO_SECRET_KEY` env var). Whitespace is trimmed; surrounding
    /// `0x`/`0X` prefixes are accepted to ease copy-paste from tools that
    /// emit them.
    pub fn from_hex(s: &str) -> Result<Self> {
        let trimmed = s.trim();
        let cleaned = trimmed
            .strip_prefix("0x")
            .or_else(|| trimmed.strip_prefix("0X"))
            .unwrap_or(trimmed);
        if cleaned.len() != 64 {
            return Err(MaestroError::Config(format!(
                "MAESTRO_SECRET_KEY must be exactly 64 hex characters (32 bytes); got {} chars",
                cleaned.len()
            )));
        }
        let raw = hex::decode(cleaned).map_err(|e| {
            MaestroError::Config(format!("MAESTRO_SECRET_KEY is not valid hex: {e}"))
        })?;
        let bytes: [u8; 32] = raw
            .try_into()
            .map_err(|_| MaestroError::Config("MAESTRO_SECRET_KEY decoded to wrong length".into()))?;
        Ok(Self(bytes))
    }

    /// Wrap a 32-byte slice. Used by tests and the keyfile bootstrap path.
    pub fn from_bytes(b: [u8; 32]) -> Self {
        Self(b)
    }

    /// Generate a fresh 32-byte key from the OS CSPRNG.
    pub fn generate() -> Result<Self> {
        let mut buf = [0u8; 32];
        getrandom::fill(&mut buf).map_err(|e| {
            MaestroError::Config(format!("CSPRNG failure while generating master key: {e}"))
        })?;
        Ok(Self(buf))
    }

    /// Raw 32-byte view for the AEAD primitive. The reference is short-lived
    /// — never copy these bytes into a long-lived `Vec`.
    pub(crate) fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Where the master key came from. The boot logger emits one of these so
/// operators can confirm their secret resolution chain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MasterKeySource {
    /// `MAESTRO_SECRET_KEY` env var.
    Env,
    /// `${data_dir}/secret.key` file already on disk.
    Keyfile,
    /// A fresh key was generated and persisted to `${data_dir}/secret.key`.
    AutoGenerated,
}

/// Returned by [`load_or_init_master_key`].
pub struct LoadedMasterKey {
    pub key: MasterKey,
    pub source: MasterKeySource,
    /// `true` when the on-disk keyfile permissions are NOT `0600` (Unix only;
    /// always `false` on non-Unix). The caller surfaces this as a critical
    /// `SystemStatus` warning so operators know the cold-disk-leak mitigation
    /// is degraded.
    pub keyfile_world_readable: bool,
}

impl std::fmt::Debug for LoadedMasterKey {
    /// Custom Debug so the inner `MasterKey` stays redacted.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LoadedMasterKey")
            .field("key", &self.key)
            .field("source", &self.source)
            .field("keyfile_world_readable", &self.keyfile_world_readable)
            .finish()
    }
}

/// Resolution order: env var → keyfile → auto-generate (if allowed).
///
/// Never panics; every failure path is a typed `Err`.
///
/// Path 1 (`MAESTRO_SECRET_KEY`):
///   - Skip if env var is unset or empty.
///   - Reject if present-but-malformed (returns `Err`).
///
/// Path 2 (`${data_dir}/secret.key`):
///   - File missing → fall through to path 3.
///   - File present but wrong size → `Err`.
///   - File present with permissive perms → load it but flag
///     `keyfile_world_readable = true`.
///
/// Path 3 (auto-generate):
///   - Only runs when `allow_auto_generate == true`.
///   - Writes the new key to `${data_dir}/secret.key` with mode `0600`.
pub fn load_or_init_master_key(
    data_dir: &Path,
    allow_auto_generate: bool,
) -> Result<LoadedMasterKey> {
    // ── 1. Env var ────────────────────────────────────────────────────────
    if let Ok(env_val) = std::env::var("MAESTRO_SECRET_KEY")
        && !env_val.trim().is_empty()
    {
        let key = MasterKey::from_hex(&env_val)?;
        return Ok(LoadedMasterKey {
            key,
            source: MasterKeySource::Env,
            // Env vars are not on cold disk; the world-readable flag concerns
            // ${data_dir}/secret.key, not the environment.
            keyfile_world_readable: false,
        });
    }

    let keyfile = data_dir.join("secret.key");

    // ── 2. Keyfile ────────────────────────────────────────────────────────
    if keyfile.exists() {
        return load_from_keyfile(&keyfile);
    }

    // ── 3. Auto-generate ──────────────────────────────────────────────────
    if !allow_auto_generate {
        return Err(MaestroError::Config(format!(
            "master key unavailable: MAESTRO_SECRET_KEY is unset and {} does not exist; \
             auto-generation is disabled ([general] allow_auto_generate_secret_key = false)",
            keyfile.display()
        )));
    }

    let key = MasterKey::generate()?;
    write_keyfile(&keyfile, &key)?;
    Ok(LoadedMasterKey {
        key,
        source: MasterKeySource::AutoGenerated,
        keyfile_world_readable: false,
    })
}

fn load_from_keyfile(path: &Path) -> Result<LoadedMasterKey> {
    let mut bytes = std::fs::read(path).map_err(|e| {
        MaestroError::Config(format!("failed to read master keyfile {}: {e}", path.display()))
    })?;
    if bytes.len() != 32 {
        // Zeroise the buffer before bailing.
        bytes.zeroize();
        return Err(MaestroError::Config(format!(
            "master keyfile {} has wrong size {} (expected 32 bytes)",
            path.display(),
            bytes.len()
        )));
    }
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    bytes.zeroize();
    let key = MasterKey::from_bytes(arr);

    let world_readable = check_world_readable(path);

    Ok(LoadedMasterKey {
        key,
        source: MasterKeySource::Keyfile,
        keyfile_world_readable: world_readable,
    })
}

/// Returns `true` when the file mode is anything other than `0600` on Unix.
/// Always `false` on non-Unix (no POSIX permission bits there).
fn check_world_readable(path: &Path) -> bool {
    #[cfg(unix)]
    {
        match std::fs::metadata(path) {
            Ok(meta) => {
                let mode = meta.permissions().mode() & 0o777;
                mode != 0o600
            }
            Err(_) => false,
        }
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        false
    }
}

#[cfg(unix)]
fn write_keyfile(path: &Path, key: &MasterKey) -> Result<()> {
    let mut f = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
        .map_err(|e| {
            MaestroError::Config(format!(
                "failed to create master keyfile {}: {e}",
                path.display()
            ))
        })?;
    f.write_all(key.as_bytes()).map_err(|e| {
        MaestroError::Config(format!("failed to write master keyfile {}: {e}", path.display()))
    })?;
    f.sync_all().map_err(|e| {
        MaestroError::Config(format!("failed to fsync master keyfile {}: {e}", path.display()))
    })?;
    Ok(())
}

#[cfg(not(unix))]
fn write_keyfile(path: &Path, key: &MasterKey) -> Result<()> {
    let mut f = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|e| {
            MaestroError::Config(format!(
                "failed to create master keyfile {}: {e}",
                path.display()
            ))
        })?;
    f.write_all(key.as_bytes()).map_err(|e| {
        MaestroError::Config(format!("failed to write master keyfile {}: {e}", path.display()))
    })?;
    f.sync_all().ok();
    Ok(())
}

/// Default name of the on-disk master key file under `data_dir`.
pub const KEYFILE_NAME: &str = "secret.key";

/// Convenience: absolute path of the master keyfile under `data_dir`.
pub fn keyfile_path(data_dir: &Path) -> PathBuf {
    data_dir.join(KEYFILE_NAME)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;
    use tempfile::tempdir;

    /// Tests in this module manipulate the process-global `MAESTRO_SECRET_KEY`
    /// env var; serialise them so they don't race each other.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn clear_env() {
        // SAFETY: tests in this module are serialised via ENV_LOCK.
        unsafe {
            std::env::remove_var("MAESTRO_SECRET_KEY");
        }
    }

    fn set_env(value: &str) {
        // SAFETY: serialised via ENV_LOCK.
        unsafe {
            std::env::set_var("MAESTRO_SECRET_KEY", value);
        }
    }

    #[test]
    fn from_hex_round_trips_canonical_form() {
        let s = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
        let key = MasterKey::from_hex(s).unwrap();
        let mut expected = [0u8; 32];
        for (i, b) in expected.iter_mut().enumerate() {
            *b = (i as u8 % 16) << 4 | ((i as u8 + 1) % 16);
        }
        // Just confirm we got 32 bytes back.
        assert_eq!(key.as_bytes().len(), 32);
    }

    #[test]
    fn from_hex_accepts_0x_prefix() {
        let s = "0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
        let key = MasterKey::from_hex(s).unwrap();
        assert_eq!(key.as_bytes().len(), 32);
    }

    #[test]
    fn from_hex_rejects_wrong_length() {
        assert!(MasterKey::from_hex("deadbeef").is_err());
        assert!(MasterKey::from_hex("").is_err());
        // 65 chars (odd).
        assert!(MasterKey::from_hex(&"0".repeat(65)).is_err());
    }

    #[test]
    fn from_hex_rejects_non_hex_chars() {
        let s = format!("z{}", "0".repeat(63));
        assert!(MasterKey::from_hex(&s).is_err());
    }

    #[test]
    fn debug_redacts_key_bytes() {
        let key = MasterKey::from_bytes([0xAAu8; 32]);
        let s = format!("{key:?}");
        assert!(s.contains("redacted"), "Debug must redact, got: {s}");
        // The literal AA byte pattern must never appear in Debug output.
        assert!(!s.contains("aa"));
        assert!(!s.contains("AA"));
    }

    #[test]
    fn load_uses_env_var_when_present() {
        let _g = ENV_LOCK.lock().unwrap();
        let dir = tempdir().unwrap();
        let hex = "f".repeat(64);
        set_env(&hex);

        let loaded = load_or_init_master_key(dir.path(), false).expect("env path must succeed");
        assert_eq!(loaded.source, MasterKeySource::Env);
        assert_eq!(loaded.key.as_bytes(), &[0xFFu8; 32]);
        assert!(!loaded.keyfile_world_readable);
        // We did NOT create a keyfile when the env var was set.
        assert!(!dir.path().join("secret.key").exists());

        clear_env();
    }

    #[test]
    fn load_rejects_malformed_env_var() {
        let _g = ENV_LOCK.lock().unwrap();
        let dir = tempdir().unwrap();
        set_env("not-hex");

        let err = load_or_init_master_key(dir.path(), true)
            .expect_err("malformed env var must reject");
        assert!(err.to_string().contains("64 hex characters"));

        clear_env();
    }

    #[test]
    fn load_reads_existing_keyfile() {
        let _g = ENV_LOCK.lock().unwrap();
        clear_env();
        let dir = tempdir().unwrap();
        let keyfile = dir.path().join("secret.key");

        // Pre-seed the keyfile.
        let raw = [0xCCu8; 32];
        std::fs::write(&keyfile, raw).unwrap();
        #[cfg(unix)]
        {
            std::fs::set_permissions(
                &keyfile,
                std::fs::Permissions::from_mode(0o600),
            )
            .unwrap();
        }

        let loaded = load_or_init_master_key(dir.path(), false)
            .expect("existing keyfile path must succeed");
        assert_eq!(loaded.source, MasterKeySource::Keyfile);
        assert_eq!(loaded.key.as_bytes(), &raw);
        assert!(!loaded.keyfile_world_readable);
    }

    #[test]
    #[cfg(unix)]
    fn load_flags_world_readable_keyfile() {
        let _g = ENV_LOCK.lock().unwrap();
        clear_env();
        let dir = tempdir().unwrap();
        let keyfile = dir.path().join("secret.key");
        std::fs::write(&keyfile, [0xDDu8; 32]).unwrap();
        std::fs::set_permissions(&keyfile, std::fs::Permissions::from_mode(0o644)).unwrap();

        let loaded = load_or_init_master_key(dir.path(), false).unwrap();
        assert_eq!(loaded.source, MasterKeySource::Keyfile);
        assert!(
            loaded.keyfile_world_readable,
            "0644 keyfile must be flagged as world-readable"
        );
    }

    #[test]
    fn load_auto_generates_when_allowed() {
        let _g = ENV_LOCK.lock().unwrap();
        clear_env();
        let dir = tempdir().unwrap();
        let keyfile = dir.path().join("secret.key");
        assert!(!keyfile.exists());

        let loaded = load_or_init_master_key(dir.path(), true).expect("auto-gen must succeed");
        assert_eq!(loaded.source, MasterKeySource::AutoGenerated);
        assert!(keyfile.exists());
        // Persisted file is 32 bytes long.
        let bytes = std::fs::read(&keyfile).unwrap();
        assert_eq!(bytes.len(), 32);
        // And the in-memory key matches what's on disk.
        assert_eq!(loaded.key.as_bytes(), bytes.as_slice());

        // Permissions are 0600 on Unix.
        #[cfg(unix)]
        {
            let mode = std::fs::metadata(&keyfile).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "auto-generated keyfile must be 0600");
        }
    }

    #[test]
    fn load_refuses_auto_generate_when_disabled() {
        let _g = ENV_LOCK.lock().unwrap();
        clear_env();
        let dir = tempdir().unwrap();
        let err = load_or_init_master_key(dir.path(), false)
            .expect_err("disabled auto-gen must reject");
        assert!(err.to_string().contains("auto-generation is disabled"));
        // And no file was written.
        assert!(!dir.path().join("secret.key").exists());
    }

    #[test]
    fn load_rejects_wrong_size_keyfile() {
        let _g = ENV_LOCK.lock().unwrap();
        clear_env();
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("secret.key"), b"too-short").unwrap();
        let err =
            load_or_init_master_key(dir.path(), true).expect_err("wrong-size keyfile must reject");
        assert!(err.to_string().contains("wrong size"));
    }
}
