// Copyright 2026 Alexandre Obellianne
// Licensed under the Functional Source License 1.1 (FSL-1.1-ALv2). See LICENSE.

//! Integration tests for `Database::open`'s master-key bootstrap
//! interaction. These live in their own file so they can manipulate the
//! `MAESTRO_SECRET_KEY` env var without racing against the rest of the
//! `auth::master_key` unit tests.

#![cfg(test)]
// Test-only `std::env` mutation (unsafe in the 2024 edition); serialised via ENV_LOCK.
#![allow(unsafe_code)]

use std::sync::Mutex;
use tempfile::tempdir;

use crate::auth::MasterKeySource;
use crate::db::Database;

static ENV_LOCK: Mutex<()> = Mutex::new(());

fn clear_env() {
    // SAFETY: serialised via ENV_LOCK.
    unsafe {
        std::env::remove_var("MAESTRO_SECRET_KEY");
    }
}

// Database::open builds a sqlx pool via `connect_lazy_with` which requires
// a Tokio runtime context (sqlx panics otherwise — see
// sqlx-core/src/pool/inner.rs), so these tests must be `#[tokio::test]`.
#[tokio::test]
async fn database_open_auto_generates_keyfile_when_allowed() {
    let _g = ENV_LOCK.lock().unwrap();
    clear_env();
    let dir = tempdir().unwrap();

    let db = Database::open(dir.path(), true).expect("open db");
    let state = db.master_key().expect("master key state");
    assert_eq!(state.source, MasterKeySource::AutoGenerated);
    assert!(!state.keyfile_world_readable);
    assert!(dir.path().join("secret.key").exists());
}

#[tokio::test]
async fn database_open_returns_no_master_key_when_disabled_and_missing() {
    let _g = ENV_LOCK.lock().unwrap();
    clear_env();
    let dir = tempdir().unwrap();

    let db = Database::open(dir.path(), false).expect("open db");
    assert!(
        db.master_key().is_none(),
        "master key must be None when auto-gen disabled and no key source present"
    );
    // The database itself opened fine — degraded mode is the intended path.
    assert!(db.data_dir().is_some());
}

#[tokio::test]
async fn database_open_reads_subsequent_keyfile_after_first_auto_generate() {
    let _g = ENV_LOCK.lock().unwrap();
    clear_env();
    let dir = tempdir().unwrap();

    // First open: auto-generates.
    let first = Database::open(dir.path(), true).expect("open 1");
    let first_bytes = std::fs::read(dir.path().join("secret.key")).unwrap();

    // Second open: must reuse the existing keyfile, not regenerate.
    let second = Database::open(dir.path(), true).expect("open 2");
    let second_bytes = std::fs::read(dir.path().join("secret.key")).unwrap();
    assert_eq!(first_bytes, second_bytes, "keyfile must persist across opens");
    assert_eq!(
        second.master_key().map(|s| s.source),
        Some(MasterKeySource::Keyfile),
        "second open must report Keyfile, not AutoGenerated"
    );
    // Both instances see the same key bytes.
    assert_eq!(
        first.master_key().unwrap().key.as_bytes(),
        second.master_key().unwrap().key.as_bytes()
    );
}
